In [1]:
import numpy as np

A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,1,0,1]).reshape(2,2)

# 행렬곱
print('※ 행렬곱')
print(A.dot(B), end='\n\n')
# print(np.dot(A,B), end='\n\n') 같은 결과


# 전치행렬
print('※ 전치행렬')
print(A.transpose(), end='\n\n')
# print(np.transpose(A), end='\n\n') 같은 결과

# 역행렬
print('※ 역행렬')
print(np.linalg.inv(A), end='\n\n')

# 행렬식
print('※ 행렬식')
print(np.linalg.det(A))

※ 행렬곱
[[0 1]
 [6 5]]

※ 전치행렬
[[0 2]
 [1 3]]

※ 역행렬
[[-1.5  0.5]
 [ 1.   0. ]]

※ 행렬식
-2.0
